import { lazy, Suspense, useEffect } from 'react';
import { Link, Route, Routes, useLocation } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Activity, MoveUpRight } from 'lucide-react';
import { AGENTS } from '../shared/domain';
const Arena = lazy(() => import('./Arena'));

export function Logo() { return <Link to="/" className="brand" aria-label="DreamCurve home"><span className="brand-mark"><Activity size={25} strokeWidth={3}/></span>dreamcurve<span className="brand-dot">.</span></Link>; }
function ScrollTop() { const {pathname} = useLocation(); useEffect(() => { window.scrollTo(0, 0); }, [pathname]); return null; }
export function MiniChart({className = ''}: {className?: string}) { return <svg className={className} viewBox="0 0 460 180" fill="none" role="img" aria-label="Illustrative probability curve trending upward"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#b7eb68" stopOpacity=".25"/><stop offset="1" stopColor="#b7eb68" stopOpacity="0"/></linearGradient></defs><path d="M0 143 15 137 26 145 38 125 50 130 63 107 74 119 84 102 96 112 107 86 116 95 127 89 137 106 149 86 160 95 172 76 184 85 195 68 206 77 220 50 233 64 244 48 257 69 268 53 279 64 291 40 303 48 314 31 326 42 338 26 350 36 360 20 374 37 388 26 400 41 414 29 427 36 442 14 460 24V180H0Z" fill="url(#chart-fill)"/><path d="M0 143 15 137 26 145 38 125 50 130 63 107 74 119 84 102 96 112 107 86 116 95 127 89 137 106 149 86 160 95 172 76 184 85 195 68 206 77 220 50 233 64 244 48 257 69 268 53 279 64 291 40 303 48 314 31 326 42 338 26 350 36 360 20 374 37 388 26 400 41 414 29 427 36 442 14 460 24" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round"/></svg>; }
function Landing() { return <>
  <header className="landing-header wrap"><Logo/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#agents">Meet the agents</a><Link to="/app/leaderboard?mode=demo">Leaderboard <ArrowUpRight size={13}/></Link></nav><Link to="/app" className="button dark small">Launch app <ArrowUpRight size={16}/></Link></header>
  <main id="main-content" tabIndex={-1}>
    <section className="hero wrap">
      <div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> A NEW PERSPECTIVE ON PREDICTION MARKETS</span><h1>Less guesswork.<br/>A clearer <span className="edge-word">edge<svg viewBox="0 0 300 30" aria-hidden="true"><path d="M4 18Q120 1 290 12M30 27Q160 7 272 23"/></svg></span>.</h1><p>Different minds. One market. Discover transparent prediction agents, compare their reasoning, and make your next move on DreamDEX.</p><div className="hero-actions"><Link to="/app" className="button primary">Find your edge <ArrowUpRight size={19}/></Link><a href="#how-it-works" className="text-link">See how it works <ArrowRight size={17}/></a></div><div className="hero-assurance"><span><span className="tiny-check">✓</span> Your wallet. Your decisions.</span><span><span className="tiny-check">✓</span> Built on Somnia</span></div></div>
      <div className="hero-visual" role="img" aria-label="Illustrative agent comparison interface">
        <div className="visual-grid"/>
        <div className="orbit orbit-one"/><div className="orbit orbit-two"/>
        <div className="preview-window"><div className="preview-top"><span className="coin bitcoin">₿</span><div><strong>Bitcoin</strong><span>15-minute event contract</span></div><span className="example-label">EXAMPLE</span></div><div className="preview-question">Will BTC finish above $97,400?</div><div className="preview-numbers"><div><span>Market probability</span><strong>61<span>%</span><small>YES</small></strong></div><div className="chart-move"><MoveUpRight size={14}/> +8.2 pp</div></div><div className="preview-graph"><div className="graph-grid"/><MiniChart/></div><div className="preview-axis"><span>14:00</span><span>14:05</span><span>14:10</span><span>14:15</span></div><div className="preview-bottom"><span><span className="status-dot"/> DreamDEX Event Contracts</span><span>Illustrative preview</span></div></div>
        <div className="floating-agent"><span className="agent-avatar lime">A<span>✳</span></span><div><strong>Atlas sees an opportunity</strong><p>Probability model · Reasoning included</p></div><span className="agent-edge">YES <ArrowUpRight size={16}/></span></div>
        <div className="floating-note"><span className="note-stars">✳</span><div><strong>Four perspectives.<br/>Your call.</strong><span>Explore the agent arena</span></div></div>
        <div className="visual-caption">MODEL REASONING, MADE VISIBLE.</div>
      </div>
    </section>
    <section className="partner-strip"><div className="wrap"><span>THE NEXT WAVE OF EVENT CONTRACTS</span><div className="partner-name"><span className="somnia-symbol">≋</span> somnia</div><span className="partner-times">×</span><div className="partner-name dreamdex">◈ DreamDEX</div><span className="partner-note">On-chain markets.<br/>Open possibilities.</span></div></section>
    <section id="how-it-works" className="section wrap"><div className="section-heading"><div><span className="eyebrow">FROM CURIOSITY TO CONVICTION</span><h2>A better way to<br/>make your next move.</h2></div><p>The market gives you a price.<br/>We help you see the perspectives behind it.</p></div><div className="steps-grid">{[{n:'01',icon:'↗',title:'Explore the possibilities',body:'Find BTC and ETH event contracts. See the price, the odds, and exactly when each window closes.'},{n:'02',icon:'✳',title:'Get another perspective',body:'Compare four transparent agents. Understand the inputs, inspect the reasoning, and see where they disagree.'},{n:'03',icon:'⌁',title:'Make it your move',body:'Choose a side, review the quote, and sign with your wallet. Come back to see how each prediction measured up.'}].map(s=><article key={s.n} className="step-card"><div><span className="step-icon">{s.icon}</span><span className="step-number">{s.n} /</span></div><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></section>
    <section id="agents" className="agents-section"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">MEET YOUR SECOND OPINIONS</span><h2>One market.<br/>More ways to see it.</h2></div><Link to="/app/agents?mode=demo" className="button outline">Explore the agents <ArrowUpRight size={17}/></Link></div><div className="landing-agents">{AGENTS.map(a=><Link to={`/app/agents?mode=demo&agent=${a.id}`} className="landing-agent" key={a.id}><div className={`agent-avatar large ${a.color}`}>{a.initial}<span>✳</span></div><span className="agent-role">{a.role.toUpperCase()}</span><h3>{a.name} <ArrowUpRight size={20}/></h3><p>{a.description}</p><span className="agent-card-link">View methodology <ArrowRight size={15}/></span></Link>)}</div><p className="quiet-note">Rule-based quantitative models. Open methodology. No promises of returns.</p></div></section>
    <section className="section wrap proof-section"><div className="proof-illustration"><div className="receipt"><span className="eyebrow">THE PREDICTION RECEIPT</span><div className="receipt-title">A forecast should<br/>have a follow-up.<span>↴</span></div><div><span>01 · BEFORE</span><strong>Record the prediction</strong></div><div><span>02 · AFTER</span><strong>Read the settled outcome</strong></div><div><span>03 · ALWAYS</span><strong>Show the full picture</strong></div><p>Timestamp · Model version · Brier score</p></div></div><div className="proof-copy"><span className="eyebrow">ACCOUNTABILITY IS THE EDGE</span><h2>Good reasoning.<br/>An open record.</h2><p>Every scored forecast is saved before the market closes. When the outcome arrives, predictions get a Brier score—so you can see how well confidence matched reality.</p><ul><li><span>✓</span> Forecasts saved before settlement</li><li><span>✓</span> Sample size shown alongside every score</li><li><span>✓</span> Paper results clearly separated from real trades</li></ul><Link to="/app/leaderboard?mode=demo" className="text-link">Explore the scorecard <ArrowRight size={17}/></Link></div></section>
    <section className="cta-section wrap"><div><span className="eyebrow">YOUR NEXT PERSPECTIVE STARTS HERE</span><h2>The future isn’t certain.<br/>Your process can be clearer.</h2><Link to="/app" className="button dark">Enter the arena <ArrowUpRight size={18}/></Link></div><div className="cta-glyph" aria-hidden="true">✳</div></section>
  </main><Footer/>
  </>; }
export function Footer() { return <footer className="footer wrap"><div><Logo/><p>Different minds. One market.</p></div><div><a href="https://github.com/somnia-chain/dreamdex-bot-kit" target="_blank" rel="noreferrer">DreamDEX resources <ArrowUpRight size={13}/></a><Link to="/methodology">Methodology</Link><Link to="/app?mode=live">Shannon testnet <span className="status-dot"/></Link></div><p className="footer-bottom">Built for Somnia × DreamDEX · Testnet only. Event contracts can expire worthless.</p></footer>; }
function Methodology(){return <><header className="landing-header wrap"><Logo/><Link className="button dark small" to="/app">Launch app <ArrowUpRight size={15}/></Link></header><main className="methodology wrap"><span className="eyebrow">OPEN BY DESIGN</span><h1>Know the model.<br/>Own the decision.</h1><p className="intro">DreamCurve compares deterministic quantitative baselines. These models have not been independently calibrated or proven to produce returns.</p>{AGENTS.map(a=><section key={a.id}><div className={`agent-avatar ${a.color}`}>{a.initial}</div><h2>{a.name} / {a.role}</h2><p>{a.description}</p><p>{a.id==='probability'?'Atlas estimates short-horizon probability using log distance to strike divided by observed volatility and square-root time. A logistic approximation transforms this score to a probability. It needs at least 12 price samples with non-zero variance.':a.id==='momentum'?'Flux starts from Atlas and applies a bounded adjustment based on recent log returns. The adjustment is capped at 12 percentage points.':a.id==='flow'?'Echo starts from the midpoint of a two-sided YES order book and adds a top-five depth imbalance adjustment capped at 8 percentage points.':'Nexus averages Atlas, Flux and Echo with equal weights. This version does not learn weights or invoke an LLM.'}</p></section>)}<section><h2>How we score</h2><p>We save at most one canonical forecast per agent and market during the final 20% of a window, capped at 60 seconds before expiry. A database constraint prevents replacement. This is an application-level record, not an on-chain timestamp commitment. Its SHA-256 digest allows an exported record to be compared; it does not prevent a database administrator from rewriting history.</p><p>Brier score = (predicted YES probability − actual YES outcome)². Lower is better. Paper PnL assumes one share at the captured executable ask, before fees and gas, with no guaranteed fill. We display every resolved canonical forecast, including NO TRADE predictions, and show sample counts.</p></section><section><h2>Trading and data</h2><p>Signals require fresh data, an open market, expiry headroom and at least a 3 percentage-point margin over the executable ask. Market odds are quoted prices, not true probabilities. Orders use exact integers, are checked against current on-chain state and are signed only in your wallet. A submitted transaction is not a successful fill.</p><p>Illustrative mode uses synthetic data and disables wallet trades. Live mode reads DreamDEX on Shannon, chain 50312. If the data service is unavailable, the app shows the failure instead of inserting demo data.</p><a className="text-link" href="https://www.npmjs.com/package/@somnia-chain/markets-sdk" target="_blank" rel="noreferrer">Read the SDK reference <ArrowUpRight size={15}/></a></section></main><Footer/></>;} 
function MethodologyRoute(){return <div id="main-content" tabIndex={-1}><Methodology/></div>}
export default function App(){return <><nav aria-label="Skip links"><a href="#main-content" className="skip-link">Skip to content</a></nav><ScrollTop/><Suspense fallback={<main id="main-content" tabIndex={-1} className="fatal" role="status">Opening your next perspective…</main>}><Routes><Route path="/" element={<Landing/>}/><Route path="/methodology" element={<MethodologyRoute/>}/><Route path="/app/*" element={<Arena/>}/><Route path="*" element={<main id="main-content" tabIndex={-1} className="fatal"><h1>This window doesn’t exist.</h1><Link className="button primary" to="/">Back home <ArrowRight size={18}/></Link></main>}/></Routes></Suspense></>;} 
